/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_huys_dll_HelloJNI */

#ifndef _Included_org_huys_dll_HelloJNI
#define _Included_org_huys_dll_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_huys_dll_HelloJNI
 * Method:    widthInBits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_huys_dll_HelloJNI_widthInBits
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
